### ISSUE TITLE
Add Schema Files to Repository

### ISSUE THREAD

**Issue by JensPfeifle** [admin-shell/io#1]
In the implementation of software supporting the AAS, having the various schema files would be very helpful.  Currently, as far as I can tell, the only way to access the schemas is to copy them from the VWSiD documents, which is a rather tedious and error-prone process...

Would you consider uploading the schema files for JSON, XML, RDF, etc. here?

**Comment by JoergWende** [comment]
No problem for the XML/XSD part. You can get it from here https://github.com/JoergWende/vwsid_xsd already.
Cheers
Jörg

**Comment by JoergWende** [comment]
@aorzelskiGH do you accecpt pull requests?
J.

**Comment by admin-shell** [comment]
At the moment I do not know how to do the pull request. Please send me an explanation by email first.

**Comment by admin-shell** [comment]
For the upload of the schemas we are checking the licensing at the moment.

**Comment by g1zzm0** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by BirgitBoss** [comment]
For V3.0RC01 of part 1 of the specification of the Asset Administration Shell the Schemas (including xmi) are now available in https://github.com/admin-shell-io/aas-specs

I close this issue. Feel free to reopen it if there are any open points.

**Comment by JensPfeifle** [comment]
Thank you :+1:
